name: Deploy

on:
  push:
    branches: [ "main" ] #whenever a push is made to main branch or a branch is merged into main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t shikhar2003/ci-cd-basics
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    - run: docker push shikhar2003/ci-cd-basics:latest

